name: DesiCore
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a91ba'
    - '#344a62'
    - '#fbfbfd'
    - '#b2c2d1'
    - '#000004'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
